name: Security

on:
  pull_request:
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security:
    uses: wefaber/.github/.github/workflows/security.yml@main
